### ISSUE TITLE
EM comparison page not working

### ISSUE THREAD

**Issue by neilriley-NOAA** [nwfsc-fram/boatnet#2390]
EM comparison page not working. Example tripNum = 100308

**Comment by sethgerou-noaa** [comment]
should be working now.

When we switched to require wcgop code be a number the wcgop-code-to-pacfin-code cross walk and the ifq-grouping lookup broke - made sure wcgop code is a number everywhere and the queries expect a number.

submitting new review data 'should' correct the logbook data for a given trip, but I haven't confirmed this yet.

**Comment by neilriley-NOAA** [comment]
@sethgerou-noaa the comparison screen is still not working in Prod. example 100319. Neither logbook or Review data is displayed.

**Comment by neilriley-NOAA** [comment]
looks like the comparison screen is working again.  Can you detail how the logbook review difference, is being calculated in trip 100308? I am unable to replicate the results displayed for the trip. Also, it should display the difference for each species grouping.

![image](https://user-images.githubusercontent.com/31421964/126573184-5f8869f4-1ab6-49fd-8a6a-67298ca78141.png)

**Comment by sethgerou-noaa** [comment]
hmm, weird.
You would expect the Diff Review Logbook column to have 500% for Pacific Whiting, correct?
What would you want to see in that column when the grouping isn't present in the logbook or review data?

**Comment by neilriley-NOAA** [comment]
Duh. The original is right. I am forgetting my basic algebra.

|V1−V2|[(V1+V2)2]×100=% difference

Initiall am not sure how to display the difference when there is nothing is reported. The percent difference requires a value greater than zero. but we need to make these comparisons when applying the pass fail rules. I am not sure if a zero is better than a null. may be worth talking this one through.

**Comment by neilriley-NOAA** [comment]
This working now.
